/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Mantenimiento;

import DAO.DAOComprobante;
import DAO.DAOUsuarios;
import DAO.DAOProducto;
import DAO.DAOVentas;
import Entidades.Comprobante;
import Entidades.DET_Venta;
import Entidades.Usuario;
import Entidades.Producto;
import Entidades.Venta;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reant
 */
public class MantVentas extends javax.swing.JFrame {

   private Venta nueva;
    /*
     * Creates new form MantVentas
     */
    public MantVentas() {
        initComponents();
        Actualizar_TablaVenta();
        CargarEmpleados();
        CargarProductos();
        Bloqueo(false);
    }


    public JComboBox<String> getCbxEmpleado() {
        return cbxusuario;
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxusuario = new javax.swing.JComboBox<>();
        btnNueva = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPaneDETV = new javax.swing.JScrollPane();
        JTableDETV = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnAgregarDETVEN = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCANTIDAD = new javax.swing.JTextField();
        cbxProductos = new javax.swing.JComboBox<>();
        btnModificarDETV = new javax.swing.JButton();
        btnBorrarDETV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtrazon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento de las Ventas");

        jLabel3.setText("Empleado:");

        btnNueva.setText("Nueva Venta");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconRefresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        JTableDETV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad", "Precio Neto"
            }
        ));
        jScrollPaneDETV.setViewportView(JTableDETV);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAgregarDETVEN.setText("Agregar Producto a la Venta");
        btnAgregarDETVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDETVENActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Producto:");

        jLabel8.setText("Cantidad:");

        txtCANTIDAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCANTIDADKeyTyped(evt);
            }
        });

        btnModificarDETV.setText("Modificar compra");
        btnModificarDETV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDETVActionPerformed(evt);
            }
        });

        btnBorrarDETV.setText("Eliminar Compra");
        btnBorrarDETV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDETVActionPerformed(evt);
            }
        });

        jLabel4.setText("Documento:");

        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Razon Social:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnAgregarDETVEN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbxusuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(24, 24, 24)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPaneDETV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnModificarDETV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBorrarDETV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtdocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                            .addComponent(txtrazon))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNueva)
                    .addComponent(cbxusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarDETVEN))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDETV, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar)
                        .addComponent(btnModificarDETV)
                        .addComponent(btnBorrarDETV))
                    .addComponent(btnCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        // TODO add your handling code here:
        nueva = new Venta();
        Bloqueo(true);
        
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Actualizar_TablaVenta();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.nueva = null;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero de Venta");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Neto");
        
        JTableDETV.setModel(modelo);
        Bloqueo(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarDETVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDETVENActionPerformed
        DAOProducto daoP = new DAOProducto();
        Producto p = daoP.BuscarporNombre(cbxProductos.getSelectedItem().toString());
        int stoc = p.getStock();
        int cant = Integer.parseInt(txtCANTIDAD.getText());
        if( cant > stoc){
            JOptionPane.showMessageDialog(rootPane, "Cantidad exceciva");
        }else{
            p.setStock(stoc-cant);
            daoP.Editar(p);
            DET_Venta nuevo = new DET_Venta(null,p, cant,0);
            
            nueva.añadir_compra(nuevo);
        }
        Ver_DETVenta(nueva.getCompras());
    }//GEN-LAST:event_btnAgregarDETVENActionPerformed

    private void txtCANTIDADKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCANTIDADKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'){
            evt.consume();
        }
    }//GEN-LAST:event_txtCANTIDADKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        DAOVentas dao = new DAOVentas();
        DAOUsuarios daoE = new DAOUsuarios();        
        Usuario u=new Usuario();
        Calendar c1= Calendar.getInstance();
        Calendar c = new GregorianCalendar();
        String dia = Integer.toString(c.get(Calendar.DATE));
        String mes = Integer.toString(c.get(Calendar.MONTH));
        String año = Integer.toString(c.get(Calendar.YEAR));
        String fechap=año+"-"+mes+"-"+dia;
        nueva.setFechaE(fechap);
        nueva.setObsventa("");
        u=daoE.BuscarporNombre(cbxusuario.getSelectedItem().toString());
        nueva.setEmpleado(u);
        Comprobante co=new Comprobante();
        
        if(txtdocumento.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
        }else if(txtdocumento.getText().length()!= 8 && txtdocumento.getText().length()!= 11){
            JOptionPane.showMessageDialog(null, "El valor dado en el campo documento es invalido");
        }else{
            if(txtdocumento.getText().length()==11){
                if(txtrazon.getText().length()<=0){
                    JOptionPane.showMessageDialog(null, "Debe completar la Razon social");
                }
                co.setRazonsocial(txtrazon.getText());
            }else{
                  co.setRazonsocial(txtrazon.getText());
            }
            DAOComprobante com=new DAOComprobante();   
            co.setFecha(fechap);
            co.setDocumento(txtdocumento.getText());
            co.setTotal(nueva.getPrecioT());
            dao.Insertar(nueva);
            com.Insertar(co);
            Bloqueo(false);
        }
        JOptionPane.showMessageDialog(null, "Venta Registrada!!");
        Actualizar_TablaVenta();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
       /* DAOVentas dao = new DAOVentas();
        DAOProducto daoP = new DAOProducto();
        int fila = JTableVentas.getSelectedRow();
        int numV = (int) JTableVentas.getValueAt(fila, 0);
        
        Venta Aux = dao.BuscarporID(numV);
        Iterator it = Aux.getCompras().iterator();
        while(it.hasNext()){
            DET_Venta temp1 = (DET_Venta) it.next();
            Producto tmp = temp1.getP();
            tmp.setStock(tmp.getStock() + temp1.getCantidad());
            daoP.Editar(tmp);
        }
        dao.Eliminar( (numV));
        Actualizar_TablaVenta();*/
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBorrarDETVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDETVActionPerformed
        
    }//GEN-LAST:event_btnBorrarDETVActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnModificarDETVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDETVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDETVActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantVentas().setVisible(true);
            }
        });
    }

    private void CargarEmpleados(){
        DAOUsuarios dao = new DAOUsuarios();
        List<Usuario> lista = dao.Listar();
        Iterator it=lista.iterator();
        while(it.hasNext()){
            Usuario aux = (Usuario) it.next();
            String item =aux.getNombre();
            cbxusuario.addItem(item);
        }
    }
    private void CargarProductos(){
        DAOProducto dao = new DAOProducto();
        List<Producto> list = dao.Listar();
        
        for(Producto tmp : list){
            cbxProductos.addItem(tmp.getProducto());
        }
    }
    private void Ver_DETVenta( List<DET_Venta> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount(lista.size());
        modelo.addColumn("Producto");
        modelo.addColumn("Precio Unitario");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio Neto");
        
        Iterator it = lista.iterator();
        int i=0;
        while(it.hasNext()){
           DET_Venta tmp= (DET_Venta) it.next();
           modelo.setValueAt(tmp.getP().getProducto(), i, 0);
           modelo.setValueAt(tmp.getP().getPrecioUni(), i, 1);
           modelo.setValueAt(tmp.getCantidad(), i, 2);
           modelo.setValueAt(tmp.getPrecioN(), i, 3);
           i++;
        }
        this.JTableDETV.setModel(modelo);
    
    }
    private void Actualizar_TablaVenta(){
        /*DefaultTableModel modelo = new DefaultTableModel();
        DAOVentas dao = new DAOVentas();
        List<Venta> lista = dao.Listar();
        Iterator it=lista.iterator();
        
        modelo.setRowCount(lista.size());
        modelo.addColumn("Numero de Venta");
        modelo.addColumn("Fecha de Emision");
        modelo.addColumn("Precio Total");
        modelo.addColumn("Empleado");
        
        int i = 0;
        while(it.hasNext()){
            Venta aux = (Venta) it.next();
            Usuario e_tmp = aux.getEmpleado();
            
            modelo.setValueAt(aux.getCodventa(), i, 0);
            modelo.setValueAt(aux.getFechaE(), i, 1);
            modelo.setValueAt(aux.getPrecioT(), i, 2);
            modelo.setValueAt(e_tmp.getNombre()+" "+e_tmp.getApellido(), i, 4);
            i++;
        }
        this.JTableVentas.setModel(modelo);*/
    }
    
    private void Bloqueo(boolean estado){
        cbxusuario.setEnabled(estado);
        btnGuardar.setEnabled(estado);
        btnAgregarDETVEN.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        this.txtCANTIDAD.setEnabled(estado);
        this.cbxProductos.setEnabled(estado);
        this.txtdocumento.setEnabled(estado);
        this.txtrazon.setEnabled(estado);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableDETV;
    private javax.swing.JButton btnAgregarDETVEN;
    private javax.swing.JButton btnBorrarDETV;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificarDETV;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JComboBox<String> cbxusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPaneDETV;
    private javax.swing.JTextField txtCANTIDAD;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtrazon;
    // End of variables declaration//GEN-END:variables
}
