/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Consultas.*;
import Vistas.Mantenimiento.MantClientes;
import Vistas.Mantenimiento.MantEmpleados;
import Vistas.Mantenimiento.MantProductos;
import Vistas.Mantenimiento.MantProveedores;
import Vistas.Mantenimiento.MantVentas;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author reant
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin() {
        initComponents();
        ColocarFondo();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconFondo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menMantenimiento = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemProductos = new javax.swing.JMenuItem();
        itemEmpleados = new javax.swing.JMenuItem();
        itemProveedores = new javax.swing.JMenuItem();
        itemVentas = new javax.swing.JMenuItem();
        menConsultas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menIProveedores = new javax.swing.JMenuItem();
        menIClientes = new javax.swing.JMenuItem();
        menIEmpleados = new javax.swing.JMenuItem();
        menIVentas = new javax.swing.JMenuItem();
        menUtilitarios = new javax.swing.JMenu();
        itemCalculadora = new javax.swing.JMenuItem();
        itemBlocNotas = new javax.swing.JMenuItem();
        menSalir = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iconFondo.setBackground(new java.awt.Color(255, 255, 255));
        iconFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menMantenimiento.setText("Mantenimiento");

        itemClientes.setText("de Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menMantenimiento.add(itemClientes);

        itemProductos.setText("de Productos");
        itemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductosActionPerformed(evt);
            }
        });
        menMantenimiento.add(itemProductos);

        itemEmpleados.setText("de Empleados");
        itemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadosActionPerformed(evt);
            }
        });
        menMantenimiento.add(itemEmpleados);

        itemProveedores.setText("de Proveedores");
        itemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedoresActionPerformed(evt);
            }
        });
        menMantenimiento.add(itemProveedores);

        itemVentas.setText("de Ventas");
        itemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentasActionPerformed(evt);
            }
        });
        menMantenimiento.add(itemVentas);

        jMenuBar.add(menMantenimiento);

        menConsultas.setText("Consultas");

        jMenuItem1.setText("de Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menConsultas.add(jMenuItem1);

        menIProveedores.setText("de Proveedores");
        menIProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIProveedoresActionPerformed(evt);
            }
        });
        menConsultas.add(menIProveedores);

        menIClientes.setText("de Clientes");
        menIClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIClientesActionPerformed(evt);
            }
        });
        menConsultas.add(menIClientes);

        menIEmpleados.setText("de Empleados");
        menIEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIEmpleadosActionPerformed(evt);
            }
        });
        menConsultas.add(menIEmpleados);

        menIVentas.setText("de Ventas");
        menIVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIVentasActionPerformed(evt);
            }
        });
        menConsultas.add(menIVentas);

        jMenuBar.add(menConsultas);

        menUtilitarios.setText("Utilititarios");

        itemCalculadora.setText("Calculadora");
        itemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalculadoraActionPerformed(evt);
            }
        });
        menUtilitarios.add(itemCalculadora);

        itemBlocNotas.setText("Bloc de Notas");
        itemBlocNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBlocNotasActionPerformed(evt);
            }
        });
        menUtilitarios.add(itemBlocNotas);

        jMenuBar.add(menUtilitarios);

        menSalir.setText("Salir");

        itemCerrarSesion.setText("Cerrar Sesion");
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        menSalir.add(itemCerrarSesion);

        ItemSalir.setText("Finalizar Sistema");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        menSalir.add(ItemSalir);

        jMenuBar.add(menSalir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColocarFondo(){
        ImageIcon fondo = new ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"));
        Icon iconoI = new ImageIcon(fondo.getImage().getScaledInstance(1880, 1000, Image.SCALE_DEFAULT));
        this.iconFondo.setIcon(iconoI);        
    }
    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login volver = new Login();
        this.setVisible(false);
        volver.setVisible(true);
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void itemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalculadoraActionPerformed
        // TODO add your handling code here:
        try {
            Runtime rt = Runtime.getRuntime();           
            Process p = rt.exec("calc");            
            p.waitFor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemCalculadoraActionPerformed

    private void itemBlocNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBlocNotasActionPerformed
        // TODO add your handling code here:
        try {
            Runtime rt = Runtime.getRuntime();           
            Process p = rt.exec("notepad");            
            p.waitFor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemBlocNotasActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        // TODO add your handling code here:
        MantClientes ventana = new MantClientes();
        ventana.setTitle("Mantenimiento de los Clientes");
        ventana.setVisible(true);
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedoresActionPerformed
        // TODO add your handling code here:
        MantProveedores mantproveedores = new MantProveedores();
        mantproveedores.setTitle("Mantenimiento de los Proveedores");
        mantproveedores.setVisible(true);
    }//GEN-LAST:event_itemProveedoresActionPerformed

    private void itemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadosActionPerformed
        // TODO add your handling code here:
        MantEmpleados vent = new MantEmpleados();
        vent.setTitle("Mantenimiento de Empleados");
        vent.setVisible(true);
    }//GEN-LAST:event_itemEmpleadosActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        // TODO add your handling code here:
        MantProductos vent = new MantProductos();
        vent.setTitle("Mantenimiento de los Productos");
        vent.setVisible(true);
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentasActionPerformed
        // TODO add your handling code here:
        MantVentas ventana = new MantVentas();
        ventana.setTitle("Mantenimiento de las ventas");
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemVentasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ConsultaProductos ventana = new ConsultaProductos();
        ventana.setTitle("Consulta de los productos");
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menIProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIProveedoresActionPerformed
        ConsultaProovedores n = new ConsultaProovedores();
        n.setTitle("Consulta de los proveedores");
        n.setLocationRelativeTo(this);
        n.setVisible(true);
    }//GEN-LAST:event_menIProveedoresActionPerformed

    private void menIClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIClientesActionPerformed
        // TODO add your handling code here:
        ConsultaClientes ventana = new ConsultaClientes();
        ventana.setTitle("Consulta de los clientes");
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        
    }//GEN-LAST:event_menIClientesActionPerformed

    private void menIEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIEmpleadosActionPerformed
        // TODO add your handling code here:
        ConsultaEmpleados ventana = new ConsultaEmpleados();
        ventana.setTitle("Consulta de los clientes");
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        
    }//GEN-LAST:event_menIEmpleadosActionPerformed

    private void menIVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIVentasActionPerformed
        // TODO add your handling code here:
        ConsultaVentas ventana = new ConsultaVentas();
        ventana.setTitle("Consulta de las ventas");
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);        
        
    }//GEN-LAST:event_menIVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrincipalAdmin admin = new PrincipalAdmin();
                admin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JLabel iconFondo;
    private javax.swing.JMenuItem itemBlocNotas;
    private javax.swing.JMenuItem itemCalculadora;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemEmpleados;
    private javax.swing.JMenuItem itemProductos;
    private javax.swing.JMenuItem itemProveedores;
    private javax.swing.JMenuItem itemVentas;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menConsultas;
    private javax.swing.JMenuItem menIClientes;
    private javax.swing.JMenuItem menIEmpleados;
    private javax.swing.JMenuItem menIProveedores;
    private javax.swing.JMenuItem menIVentas;
    private javax.swing.JMenu menMantenimiento;
    private javax.swing.JMenu menSalir;
    private javax.swing.JMenu menUtilitarios;
    // End of variables declaration//GEN-END:variables
}
